//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELib.Common.DbDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorGenre
    {
        public int Id { get; set; }
        public int AuthorId { get; set; }
        public int GenreId { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
