//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELib.Common.DbDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.BookAuthors = new HashSet<BookAuthor>();
            this.BookFormats = new HashSet<BookFormat>();
            this.BookGenres = new HashSet<BookGenre>();
            this.RatingBooks = new HashSet<RatingBook>();
            this.UserBookStatus = new HashSet<UserBookStatu>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int PublishLangId { get; set; }
        public Nullable<int> OriginalLangId { get; set; }
        public Nullable<int> TotalPages { get; set; }
        public string Isbn { get; set; }
        public int PublisherId { get; set; }
        public Nullable<System.DateTime> PublishYear { get; set; }
        public byte[] Picture { get; set; }
        public string Description { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Language Language1 { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookAuthor> BookAuthors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookFormat> BookFormats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookGenre> BookGenres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RatingBook> RatingBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBookStatu> UserBookStatus { get; set; }
    }
}
