// <auto-generated />
namespace ELib.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Link_Person_And_ApplicationUser_By_ApplicationUserId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Link_Person_And_ApplicationUser_By_ApplicationUserId));
        
        string IMigrationMetadata.Id
        {
            get { return "201509011313127_Link_Person_And_ApplicationUser_By_ApplicationUserId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
