// <auto-generated />
namespace ELib.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Person_And_ApplicationUser_Entities_Updated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Person_And_ApplicationUser_Entities_Updated));
        
        string IMigrationMetadata.Id
        {
            get { return "201509011050444_Person_And_ApplicationUser_Entities_Updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
