// <auto-generated />
namespace ELib.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FileName_Field_For_Book_Instance_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FileName_Field_For_Book_Instance_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201508230936526_FileName_Field_For_Book_Instance_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
